image: ${DOCKER_DOTNET_SDK_IMAGE}

variables:
  BUILD_FOLDER: DotNetCoreDecorators
  TEST_FOLDER: DotNetCoreDecorators.Tests

stages:
  - test
  - publish-nuget

test:
  stage: test
  script:
    - cd ${TEST_FOLDER}
    - dotnet test
  only:
    - master       

publish-nuget:
  stage: publish-nuget
  script:        
    - cd ${BUILD_FOLDER}  
    - projectfile=${BUILD_FOLDER}  
    - ver=$(cat $projectfile.csproj | grep '<Version>' | awk -F ">" '{print $2}' | awk -F"<" '{print $1}') 
    - echo $ver
    - dotnet pack $projectfile.csproj --configuration Release --output ./out-nuget 
    - dotnet nuget push ./out-nuget/$projectfile.$ver.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
  only:
    - master    
  #when: manual    

