name: Release nuget
on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release

      - name: Make pack
        run: dotnet pack --configuration Release DotNetCoreDecorators/DotNetCoreDecorators.csproj /p:Version=${GITHUB_REF#refs/tags/}

      - name: Publish the package to GPR - MyYamlParser
        run: dotnet nuget push DotNetCoreDecorators/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}
